// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecfwaymuficatdmrhfhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZndheW11ZmljYXRkbXJoZmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODYwOTgsImV4cCI6MjA2NzE2MjA5OH0.9-yWpjMuvZNDGh0DWNC3kxjBy9FWzJGzjK-uuuJrgWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});